### ISSUE TITLE
emoji换行问题

### ISSUE THREAD

**Issue by SOBER-WSR** [szrpf/RichTextDemo#1]
多行文字和emoji 换行错误

**Comment by SOBER-WSR** [comment]
安卓原生

**Comment by szrpf** [comment]
具体什么问题？必现吗？

**Comment by SOBER-WSR** [comment]
是的 安卓手机必现，this.ctx.measureText(str[i]).width 这个str【i】如果是😊😄👌这写小表情， width是0，换行就错了。

**Comment by SOBER-WSR** [comment]
比如这段文字 在手机上换行就是错误的
“1test1111我1test1111😅😆😇😈😉撒东湖区我大呼😊😋😌😍撒东湖区我大呼😅😆😇😈😉😊😋😌😍你1test1111岁呢大撒东湖区我大呼1test11111111111”

**Comment by szrpf** [comment]
这个不太好搞，因为emoji本来就是通过输入法，把文本转换成图片。
你可以试试原版RichText是否支持emoji，可以实现但没必要，因为支持直接插入图片，干嘛还要用emoji




刘飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "szrpf/RichTextDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [szrpf/RichTextDemo] emoji换行问题 (Issue #1)





 
比如这段文字 在手机上换行就是错误的
 “1test1111我1test1111😅😆😇😈😉撒东湖区我大呼😊😋😌😍撒东湖区我大呼😅😆😇😈😉😊😋😌😍你1test1111岁呢大撒东湖区我大呼1test11111111111”

**Comment by SOBER-WSR** [comment]
我是做聊天列表呢 原版的richtext性能太差  所以想用您写的这个方案
因为emoji是用户输入的 我没办法用图片代替 这个有什么解决思路吗
我试了试 宽度为0的时候 给了个指定宽度 这样换行是没问题了 但是会有几行绘制不出来 您知道这是为什么吗

**Comment by szrpf** [comment]
emoji实际上也是字符串，只是被解析成图片了。
举个栗子，123&nbsp; 对应"[得意]123"，前4个字符已经被转成emoji了，你要在updateContent遍历的时候
当前行加上该emoji图片宽度，并且跳过4个字符从123的1开始继续遍历
参考我做\c颜色值\c的代码




刘飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "szrpf/RichTextDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [szrpf/RichTextDemo] emoji换行问题 (Issue #1)





 
我是做聊天列表呢 原版的richtext性能太差  所以想用您写的这个方案
 因为emoji是用户输入的 我没办法用图片代替 这个有什么解决思路吗
 我试了试 宽度为0的时候 给了个指定宽度 这样换行是没问题了 但是会有几行绘制不出来 您知道这是为什么吗

**Comment by SOBER-WSR** [comment]
好的 我研究一下

**Comment by SOBER-WSR** [comment]
解决了 把let str = this.string 改成 let str = Array.from(this.string); 就可以了
